// config/env.ts
const e = process.env;

export const ENV = {
    // App
    APP_NAME: e.NEXT_PUBLIC_APP_NAME,
    APP_URL: e.NEXT_PUBLIC_APP_URL,
    API_URL: e.NEXT_PUBLIC_API_URL,

    // TEAM Info
    TEAM_ID: e.NEXT_PUBLIC_TEAM_ID,

    TEAM_NAME: e.NEXT_PUBLIC_TEAM_NAME,
    TEAM_ALIAS: e.NEXT_PUBLIC_TEAM_ALIAS,
    SHORT_NAME: e.NEXT_PUBLIC_APP_SHORT_NAME,
    TAGLINE: e.NEXT_PUBLIC_APP_TAGLINE,

    // Assets
    LOGO_URL: e.NEXT_PUBLIC_LOGO_URL,
    LOGO_NO_BG_URL: e.NEXT_PUBLIC_LOGO_NO_BG_URL,
    FAVICON_URL: e.NEXT_PUBLIC_FAVICON_URL,
    OFFICIAL_SIGNATURE_URL: e.NEXT_PUBLIC_OFFICIAL_SIGNATURE_URL,
    OPPONENT_LOGO_URL: e.NEXT_PUBLIC_OPPONENT_LOGO_URL,
    OPPONENT_LOGO_NO_BG_URL: e.NEXT_PUBLIC_OPPONENT_LOGO_NO_BG_URL,

    // Cloudinary
    CLOUDINARY: {
        CLOUD_NAME: e.CLOUDINARY_NAME,
        UPLOAD_PRESET: e.CLOUDINARY_UPLOAD_PRESET,
        //private
        API_KEY: e.CLOUDINARY_API_KEY,
        API_SECRET: e.CLOUDINARY_API_SECRET,
    },

    // Contact
    CONTACT: {
        EMAIL: e.NEXT_PUBLIC_CONTACT_EMAIL,
        PHONE: e.NEXT_PUBLIC_CONTACT_PHONE,
        MEDIA_EMAIL: e.NEXT_PUBLIC_MEDIA_EMAIL,
        SPONSORSHIP_EMAIL: e.NEXT_PUBLIC_SPONSORSHIP_EMAIL,
    },

    // Social
    SOCIAL: {
        FACEBOOK: e.NEXT_PUBLIC_FACEBOOK_URL,
        INSTAGRAM: e.NEXT_PUBLIC_INSTAGRAM_URL,
        TELEGRAM: e.NEXT_PUBLIC_TELEGRAM_URL,
        TWITTER: e.NEXT_PUBLIC_TWITTER_URL,
        YOUTUBE: e.NEXT_PUBLIC_YOUTUBE_URL,
        WHATSAPP: e.NEXT_PUBLIC_WHATSAPP_URL,
        TIKTOK: e.NEXT_PUBLIC_TIKTOK_URL,
    },

    AUTH_GOOGLE_ID: e.AUTH_GOOGLE_ID,
    AUTH_GOOGLE_SECRET: e.AUTH_GOOGLE_SECRET
} as const;