import { GoEye, GoEyeClosed } from "react-icons/go";
import { FaCediSign } from "react-icons/fa6";
import {
  MdOutlineKeyboardBackspace,
  MdCheckBox,
  MdCheckBoxOutlineBlank,
} from "react-icons/md";
import { VscLoading } from "react-icons/vsc";
import { LiaComment } from "react-icons/lia";
import {
  CheckCircle,
  Clock,
  AlertTriangle,
  Search,
  AlertCircle,
  Camera,
  Upload,
  X,
  ChevronDown,
  Menu,
  Printer,
  PersonStanding,
  User, Users,
  LayoutDashboard,
  Home, FileText,
  Dot,
  ExternalLink,
  Delete,
  Trash2,
  MoreHorizontal,
  Edit,
  Edit3,
  DownloadIcon,
  Loader,
  Loader2,
  RefreshCcw,
  Plus,
  Copy,
  Move,
  Users2,
  Triangle,
  XIcon,
  Save,
  Share2,
  Smile,
  Eye,
   
} from "lucide-react";

export const icons = {
  comment: LiaComment,
  view: Eye,
  smile: Smile,
  save: Save,
  share: Share2,
  copy: Copy,
  move: Move,
  new: Plus,
  refresh: RefreshCcw,
  loader: Loader2,
  loaderSpiral: Loader,
  download: DownloadIcon,
  edit: Edit,
  editPen: Edit3,
  delete: Delete,
  trash: Trash2,
  externalLink: ExternalLink,
  dot: Dot,
  group: Users2,
  user: User,
  users: Users,
  person: PersonStanding,
  printer: Printer,
  menu: Menu,
  more: MoreHorizontal,
  triangle: Triangle,
  chevron: ChevronDown,
  checked: MdCheckBox,
  unchecked: MdCheckBoxOutlineBlank,
  eyeOpen: GoEye,
  eyeClosed: GoEyeClosed,
  close: XIcon,
  loading: VscLoading,
  back: MdOutlineKeyboardBackspace,
  search: Search,
  checkCircle: CheckCircle,
  clockTime: Clock,
  alertTriange: AlertTriangle,
  alertCircle: AlertCircle,
  currency: FaCediSign,
  x: X,
  camera: Camera,
  upload: Upload,
  dashboard: LayoutDashboard,
  home: Home,
  fileText: FileText,
  tracking: FileText,
};
